repos:
  # - repo: https://github.com/pre-commit/mirrors-pytest
  #   rev: v8.2.1  # Use the latest stable version or specify as needed
  #   hooks:
  #     - id: pytest
  #       name: Run pytest
  #       entry: pytest
  #       language: system
  #       types: [python]
  #       pass_filenames: false

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.4  # Use the latest stable version or specify as needed
    hooks:
      - id: ruff
        name: Ruff code formatter
        language: system
        entry: ruff check ./src
